language: php

sudo: false

php:
- 7.0
- 7.1
- 5.6
- 5.2
- 5.3
- 5.4
- 5.5

env:
- WP_VERSION=nightly
- WP_VERSION=latest
- WP_VERSION=4.7.5
- WP_VERSION=4.7.4
- WP_VERSION=4.7.3
- WP_VERSION=4.7.2
- WP_VERSION=4.7.1
- WP_VERSION=4.7

matrix:
  allow_failures:
    - env: WP_VERSION=nightly

node_js: 6

install:
- npm install grunt-cli
- npm install
  
before_script:
- if [[ ! ( $TRAVIS_PHP_VERSION = '7.0' && $WP_VERSION = 'latest' ) ]]; then phpenv config-rm xdebug.ini || true; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
- WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit
- ln -s /tmp/wordpress src && WP_TESTS_DIR=/tmp/wordpress-tests-lib grunt --verbose test_qunit

after_success:
- if [[ $TRAVIS_PHP_VERSION = '7.0' && $WP_VERSION = 'latest' ]]; then bash bin/coverage.sh; fi
