language: php

sudo: false

php:
- 7.1
- 7.0
- 5.2
- 5.3
- 5.4
- 5.5
- 5.6

env:
- WP_VERSION=nightly
- WP_VERSION=latest

matrix:
  allow_failures:
    - env: WP_VERSION=nightly

install:
- npm install grunt-cli
- npm install
  
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
- WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit --verbose

after_success:
- if [[ ( $TRAVIS_PHP_VERSION = '7' || $TRAVIS_PHP_VERSION > '7' ) && $WP_VERSION = 'latest' ]] then
- WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit --coverage-clover clover.xml && bash <(curl -s https://codecov.io/bash)
- fi
