language: php

sudo: false

php:
- 7.1

env:
- WP_VERSION=nightly

install:
- npm install grunt-cli
- npm install
  
before_script:
- if [[ ! ( $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' ) ]]; then phpenv config-rm xdebug.ini || true; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
- ln -s /tmp/wordpress src
- grunt test_qunit

after_success:
- if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' ]]; then WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit --coverage-clover clover.xml && bash <(curl -s https://codecov.io/bash); fi
