language: php

sudo: false

php:
- 7.0

env:
- WP_VERSION=nightly
- WP_VERSION=latest
- WP_VERSION=4.7.5

matrix:
  allow_failures:
    - env: WP_VERSION=nightly

node_js: 6

install:
- npm install grunt-cli
- npm install
  
before_script:
- if [[ ! ( $TRAVIS_PHP_VERSION = '7.0' && $WP_VERSION = 'latest' ) ]]; then phpenv config-rm xdebug.ini || true; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
- WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && php wp-cli.phar --info
- ln -s /tmp/wordpress src
- WP_TESTS_DIR=/tmp/wordpress-tests-lib php wp-cli.phar gopp gen_js_fixtures --require=tools/gen_js_command.php --path=/tmp/wordpress --debug
- WP_TESTS_DIR=/tmp/wordpress-tests-lib grunt --verbose test_qunit

after_success:
- if [[ $TRAVIS_PHP_VERSION = '7.0' && $WP_VERSION = 'latest' ]]; then bash bin/coverage.sh; fi
